### ISSUE TITLE
Register Names for Adafruit Metro M4

### ISSUE THREAD

**Issue by SamRanjha** [SapientHetero/TRNG-for-ATSAMD51J19A-Adafruit-Metro-M4-#1]
Can you please tell where did you find the list of Register Names and functions that you used in your project.
![Capture](https://user-images.githubusercontent.com/30014834/58870615-2bf74d80-86de-11e9-950b-02399d038b3a.PNG)

**Comment by SapientHetero** [comment]
Sorry for the delay, but I just noticed your request.

I'm using the Arduino IDE on Windows 10 and the CMSIS declarations used to access registers can be found at:

C:\Users\[your user name]\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0\CMSIS\Device\ATMEL\samd51\include

More specifically, the declarations for the TRNG can be found at C:\Users\[your user name]\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0\CMSIS\Device\ATMEL\samd51\include\component\trng.h

I regret to say that I don't recall exactly where I found the function names. However, if you're programming for the Cortex-M4 family you can learn all kinds of useful things by looking at the Atmel Start example programs.

Hope that helps.
